export { default as CadastrarAutomovel } from './Cadastros/CadastrarAutomovel/index';
export { default as CadastrarCliente } from './Cadastros/CadastrarCliente/index';
export { default as CadastrarEndereco } from './Cadastros/CadastrarEndereco/index';
export { default as CadastrarLocacao } from './Cadastros/CadastrarLocacao/index';
export { default as CadastrarMarca } from './Cadastros/CadastrarMarca/index';
export { default as CadastrarModelo } from './Cadastros/CadastrarModelo/index';
export { default as VisualizarAutomovel} from './Visualiza/VisualizarAutomovel';
export { default as VisualizarCliente} from './Visualiza/VisualizarCliente';
export { default as VisualizarEndereco} from './Visualiza/VisualizarEndereco';
export { default as VisualizarLocacao} from './Visualiza/VisualizarLocacao';
export { default as VisualizarMarca} from './Visualiza/VisualizarMarca';
export { default as VisualizarModelo} from './Visualiza/VisualizarModelo';
