# Generated by Django 3.0.7 on 2020-06-18 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('renavam', models.CharField(max_length=45)),
                ('cor', models.CharField(max_length=45)),
                ('chassi', models.CharField(max_length=45)),
                ('tipo_combustivel', models.CharField(max_length=45)),
                ('valor_locacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('sobrenome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=14)),
                ('cnh', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_locacao', models.DateTimeField(default=datetime.datetime(2020, 6, 18, 18, 36, 56, 105162))),
                ('dt_devolucao', models.DateTimeField(blank=True, null=True)),
                ('km', models.IntegerField()),
                ('valor_calcao', models.FloatField()),
                ('valor_km', models.FloatField()),
                ('devolucao', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('valor_total', models.FloatField()),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Automovel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField()),
                ('logradouro', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='automovel',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Modelo'),
        ),
    ]
